name: 'Manager labels'
description: 'Manager labels - check label or remove label when commit'
inputs:
  token:
    description: 'Github token (GITHUB_TOKEN)'
    required: true
  required_labels:
    description: 'List of labels that must be present on Pull Request'
    required: false
    default: '[]'
  any_of_labels:
    description: 'List of labels, at least one of which must be present on Pull Request'
    required: false
    default: '[]'
  skip_labels_check:
    description: 'If the specified label appears on the PR, the process of checking the labels will be skipped.'
    required: false
    default: '[]'
runs:
  using: 'node20'
  main: 'dist/index.js'