name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy via SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
        run: |
          ssh $SSH_USER@$SSH_HOST << 'EOF'
            cd /var/www/demo-repository
            git config --global --add safe.directory /var/www/demo-repository
            git checkout $MAIN_BRANCH
            git pull
            exit
          EOF

      - name: Cleanup
        run: rm -rf ~/.ssh
