name: Check QA Dev Label Before Merge to Main

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, ready_for_review]

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is targeted to main and has QA Dev label
      uses: actions/github-script@v6
      with:
        script: |
          const prLabels = context.payload.pull_request.labels;
          const hasQaDevLabel = prLabels.some(label => label.name === 'QA Dev');
          
          if (!hasQaDevLabel) {
            core.setFailed('PR nie ma wymaganej etykiety QA Dev.');
          }

          const { owner, repo } = context.repo;
          const prNumber = context.payload.pull_request.number;

          // Pobranie listy wydarzeń związanych z PR
          const events = await github.rest.issues.listEventsForTimeline({
            owner,
            repo,
            issue_number: prNumber,
          });
          const labelAddEvent = events.data.find(event => event.event === 'labeled' && event.label.name === 'QA Dev');
          const labelRemoveEvent = events.data.find(event => event.event === 'unlabeled' && event.label.name === 'QA Dev');
          if (labelAddEvent && labelAddEvent.actor.login === context.payload.sender.login) {
            if (labelRemoveEvent.actor.login === context.payload.sender.login || labelRemoveEvent.created_at < labelAddEvent.created_at) {
              core.setFailed('Nie można samemu sobie nadać labelki QA Dev.');
            }
          }

