name: Check QA Dev Label Before Merge to Main

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, ready_for_review]

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is targeted to main and has QA Dev label
      uses: actions/github-script@v6
      with:
        script: |
          const prLabels = context.payload.pull_request.labels;
          console.log(context.payload.pull_request);
          const hasQaDevLabel = prLabels.some(label => label.name === 'QA Dev');
          
          if (!hasQaDevLabel) {
            core.setFailed('PR nie ma wymaganej etykiety QA Dev.');
          }
