name: Check QA Dev Label Before Merge to Main

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, ready_for_review]

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is targeted to main and has QA Dev label
      uses: actions/github-script@v6
      with:
        script: |
          const prLabels = context.payload.pull_request.labels;
          const hasQaDevLabel = prLabels.some(label => label.name === 'QA Dev');
          
          if (!hasQaDevLabel) {
            core.setFailed('PR nie ma wymaganej etykiety QA Dev.');
          }

          const { data: events } = await github.issues.listEventsForTimeline({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number
          });

          const labelEvent = events.reverse().find(event => 
            event.event === 'labeled' && event.label.name === 'QA Dev'
          );

          if (!labelEvent) {
            core.setFailed('Nie udało się znaleźć zdarzenia dodania etykiety QA Dev.');
            return;
          }

          const labelAddedBy = labelEvent.actor.login;
          const prAuthor = pr.user.login;

          if (labelAddedBy === prAuthor) {
            core.setFailed('Autor PR nie może dodać etykiety QA Dev do własnego PR.');
          } else {
            console.log('Etykieta QA Dev jest obecna i została dodana przez inną osobę.');
          }
