name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Install dependencies via Composer
        run: composer install
      - name: Run cs fixer
        run: composer run-script lint
      - name: Check for phpstan-baseline.neon in PR
        run: |
          if ! git diff --name-only origin/main | grep -q 'phpstan-baseline.neon'; then
            echo "Error: The phpstan-baseline.neon file is missing in the Pull Request.";
            exit 1;
          fi

