name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Install dependencies via Composer
        run: composer install
      - name: Run cs fixer
        run: composer run-script lint
      - name: Run PHPStan baseline
        run: vendor/bin/phpstan analyse --generate-baseline phpstan-baseline-ci.neon
      - name: Compare PHPStan baseline with PR's baseline
        run: |
          if ! diff -u phpstan-baseline.neon phpstan-baseline-ci.neon; then
            echo "Error: The generated phpstan-baseline.neon differs from the one provided in the PR.";
            exit 1;
          fi

