name: CI/CD

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
      - name: Install dependencies via Composer
        run: composer install
      - name: Run cs fixer
        run: composer run-script lint
      - name: Run GrumPHP
        run: |
          vendor/bin/grumphp run
  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: build-test-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /var/www/demo-repository && git config --global --add safe.directory /var/www/demo-repository
          && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit"

      - name: Cleanup
        run: rm -rf ~/.ssh
