name: Switch on dev branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose branch on dev (feat/ZGL-1000-Test)'
        required: true
        default: 'develop'

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate branch input
        run: |
          if [[ "${{ inputs.branch }}" == "develop" ]]; then
            BRANCH=${{ inputs.branch }}
          else
            BRANCH=${{ inputs.branch }}
            if ! git ls-remote --heads origin "$BRANCH" | grep "$BRANCH" >/dev/null; then
              echo "ERROR: The specified branch '$BRANCH' does not exist in the repository."
              exit 1
            fi
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Switch branch to Dev Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying branch: $BRANCH"
            cd /var/www/test/demo-repository-1
            git reset --hard
            git fetch --all
            git checkout ${{ env.BRANCH }}
            git pull
            composer install --ignore-platform-req=ext-xdebug --ignore-platform-req=ext-ldap
            php artisan migrate
            php artisan config:clear
