name: Main Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    name: Create Tag on Main
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'release/') || contains(github.event.head_commit.message, 'hotfix/')
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Extract Version from Commit Message
        id: extract_version
        run: |
          echo "VERSION=1.20.1" >> $GITHUB_ENV

      - name: Create Tag on Main
        run: |
          git tag "v${VERSION}"
          git push origin "v${VERSION}"