name: MANAGER-LABELS-WORKFLOW

on:
  pull_request:
    types: [labeled, unlabeled, synchronize]
  push:
    branches:
      - develop
      - 'feat/**'

permissions: write-all

jobs:
  manager_labels:
    name: 'ManagerLabels'
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == false &&
      (
        (github.event.pull_request.base.ref == 'develop' &&
         github.event.pull_request.head.ref != 'main')
        ||
        (github.event.pull_request.base.ref == 'main' &&
         startsWith(github.event.pull_request.head.ref, 'hotfix/'))
        ||
        startsWith(github.event.pull_request.head.ref, 'release/')
      )
      ||
      (
        github.event_name == 'push' &&
        (
          github.ref == 'refs/heads/develop' ||
          startsWith(github.ref, 'refs/heads/feat/')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Manger Labels
        uses: ./.github/actions/manager-labels
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          required_labels: '["CR1", "APPROVAL"]'
          skip_labels_check: '["DO MERGE"]'
