name: Release Deployment

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    types: [closed]

permissions: write-all

jobs:
  rollback_release:
    name: Rollback release
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rollback on PRE
        uses: appleboy/ssh-action@v0.1.5
        with: 
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test/demo-repository-2
            git reset --hard
            git fetch --all
            release_branches=$(git branch -r | grep 'release/' | sed 's/origin\///' | sort -V | sed 's/^[[:space:]]*//')
            echo "Release branches found:"
            echo "$release_branches"
            
            current_branch=$(git branch --show-current)
            echo "Current branch: $current_branch"
            previous_branch=$(echo "$release_branches" | grep -B1 "$current_branch" | head -n 1 | sed 's/^[[:space:]]*//')

            while [ ! -z "$previous_branch" ]; do
              if git show "$previous_branch:.pr_status" | grep -q "Branch zamknięty"; then
                echo "Branch $previous_branch jest oznaczony jako zamknięty. Szukam wcześniejszego."
                previous_branch=$(echo "$release_branches" | grep -B2 "$current_branch" | head -n 1 | sed 's/^[[:space:]]*//')
                current_branch=$previous_branch
              else
                break
              fi
            done

            if [ -z "$previous_branch" ]; then
              echo "Error: Nie znaleziono dostępnego brancha do rollbacku."
              exit 1
            fi

            echo "Previous release branch: $previous_branch"
            git checkout "$previous_branch"
            
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          
      - name: Mark branch as closed
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "Branch zamknięty w PR #${{ github.event.pull_request.number }}" >> .pr_status
          git checkout $BASE_BRANCH
          git pull origin $BASE_BRANCH
          git add .pr_status
          git commit -m "Oznaczenie PR zamkniętego: #${{ github.event.pull_request.number }}"
          git push origin $BASE_BRANCH
          
  deploy-to-pre:
    name: Deploy to Pre Server
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  create-pull-request:
    name: Create Pull Request to Main
    needs: deploy-to-pre
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: "Merge ${{ github.ref_name }} into main"
          labels: |
            RELEASE
