name: Release Deployment

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  deploy-to-pre:
    name: Deploy to Pre Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Test Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test/demo-repository-1
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            composer install
            php artisan migrate
            php artisan config:clear

  wait-for-approval:
    name: Await Approval
    needs: deploy-to-pre
    runs-on: ubuntu-latest
    steps:
      - name: Request Approval
        uses: peter-evans/workflow-approval@v1
        with:
          reviewers: pzyw-msoft
          timeout: 43200
          message: |
            Proszę zatwierdzić wdrożenie na produkcję.

  merge-and-tag:
    name: Merge to Main and Tag
    needs: wait-for-approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Merge release branch into main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge --no-ff ${{ github.ref }} -m "Merge ${GITHUB_REF} into main"
          git push origin main

      - name: Create Tag on main
        run: |
          VERSION=${GITHUB_REF#refs/heads/release/}
          git tag "v$VERSION"
          git push origin "v$VERSION"