name: Release Deployment

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  deploy-to-pre:
    name: Deploy to Pre Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Test Server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test/demo-repository-1
            git fetch
            git checkout ${{ github.ref_name }}
            git pull
            composer install
            php artisan migrate
            php artisan config:clear

  create-pull-request:
    name: Create Pull Request to Main
    needs: deploy-to-pre
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: main
          title: "Merge release/${{ github.ref_name }} into main"
          body: |
            Automatyczne PR z gałęzi `release/${{ github.ref_name }}` do `main` po wdrożeniu na serwer pre.