name: Release Deployment

on:
  push:
    branches:
      - 'release/**'

permissions: write-all

jobs:
  deploy-to-pre:
    name: Deploy to Pre Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  create-pull-request:
    name: Create Pull Request to Main
    needs: deploy-to-pre
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: "Merge ${{ github.ref_name }} into main"
          labels: |
            RELEASE
