name: Release Deployment

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    types: [closed]

permissions: write-all

jobs:
  jira-release1:
    name: Create release on JIRA
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/') && github.event.created == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Jira manager - create release
        uses: ./.github/actions/jira-manager
        with:
          jira_email: ${{ secrets.JIRA_EMAIL }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_url: ${{ secrets.JIRA_URL }}
          jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
          environment: ${{ vars.ENVIRONMENT }}
          jira_id_awaiting_to_testing: ${{ vars.JIRA_ID_AWAITING_TO_TESTING }}
          github_ref: ${{ github.ref }}
          type: 'createRelease'

  rollback_release:
    name: Rollback release
    if: > 
      (github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merged == false &&
      startsWith(github.event.pull_request.base.ref, 'main'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }
        
      - name: Select rollback branch
        id: branch
        run: |
          git fetch --all --prune

          # lista release/* posortowana malejąco wg numeru wersji
          release_branches=$(git for-each-ref \
            --format='%(refname:strip=3)' \
            --sort=-version:refname refs/remotes/origin/release/)

          echo "::group::Lista release branchy"
          echo "$release_branches"
          echo "::endgroup::"

          current="${{ github.event.pull_request.head.ref }}"
          echo "Zamykany branch: $current"

          for b in $release_branches; do
            # pomijamy aktualnie zamknięty branch
            [ "$b" = "$current" ] && continue

            # jeżeli istnieje .pr_status → branch uznajemy za „zamknięty”
            if git show "origin/$b:.pr_status" >/dev/null 2>&1; then
              echo "Pomijam $b – oznaczony .pr_status"
              continue
            fi

            echo "Wybrany rollback branch: $b"
            echo "target=$b" >>"$GITHUB_OUTPUT"
            exit 0
          done

          echo "Brak dostępnego brancha do rollbacku"
          exit 1

      - name: Checkout target branch
        run: |
          git fetch origin ${{ steps.branch.outputs.target }}:${{ steps.branch.outputs.target }}
          git checkout ${{ steps.branch.outputs.target }}
            
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          
      - name: Mark branch as closed
        env:
          BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          echo "Branch zamknięty w PR #${{ github.event.pull_request.number }}" >> .pr_status
          git fetch --all
          git checkout $BASE_BRANCH
          git pull origin $BASE_BRANCH
          git add .pr_status
          git commit -m "Oznaczenie PR zamkniętego: #${{ github.event.pull_request.number }}"
          git push origin $BASE_BRANCH
  
  create-version-file:
    name: Create version file
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/') && github.event.created == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'    
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          
      - name: Extract Release Version
        id: extract_version
        run: |
          echo "RELEASE_VERSION=v${GITHUB_REF##*/}" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}
        
      - name: Version update
        run: |
          # FORMATTED_VERSION=$(echo "${{ env.RELEASE_VERSION }}" | sed 's/\(.*\)\./\1-/')
          # npm version $FORMATTED_VERSION --no-git-tag-version
          git checkout ${{ github.ref_name }}
          CLEAN_VERSION=$(echo "${{ env.RELEASE_VERSION }}" | sed 's/^v//')
          jq --arg ver "$CLEAN_VERSION" '.version = $ver' package.json > temp.json && mv temp.json package.json
        env:
          BASE_BRANCH: ${{ github.event.pull_request.head.ref }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          
      - name: Commit & Push version update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "commit version to package"
          git push origin ${{ github.ref_name }}
          
  deploy-to-pre:
    name: Deploy to Pre Server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: CONSOLE LOG
        run: |
          echo "Branch or Tag Name: ${{ github.ref_name }}"
          echo "Base branch (github.base_ref): ${{ github.base_ref }}"

  create-pull-request:
    name: Create Pull Request to Main
    needs: deploy-to-pre
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: "Merge ${{ github.ref_name }} into main"
          labels: |
            RELEASE
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref }}
          title: "Merge ${{ github.ref_name }} into develop"
          labels: |
            RELEASE      
